#server:
#  port: 9001
#spring:
#  application:
#    name: leadnews-admin
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.31.132:3306/leadnews_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.31.132:8848  #配置nacos信息
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.heima.model.admin.pojos
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql